root:
  askformore: false
  autoclip: false
  autoprint: false
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  exportkeys: true
  nocolor: false
  noconfirm: false
  nopager: true
  notifications: true
  path: gpgcli-gitcli-fs+file://<some_path_to_password_store>
  recipient_hash:
    .gpg-id: <some_id>
  safecontent: false
  usesymbols: false
mounts: {}
